# Insert & update statements generated by Gen*.py scripts running against
# table DDL.
# Also staging table create statements.

insstmts = {
    # hubs
    "strategy_h":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_h
            (
                strategy_hash_key,
				record_src,
				strategy_id,
                load_dt
            )
            SELECT 
                h.strategy_hash_key,
				h.record_src,
				h.strategy_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_h tgth
                ON h.record_src = tgth.record_src
				AND h.strategy_id = tgth.strategy_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.strategy_id IS NULL
        """,
    "strategy_set_h":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_h
            (
                strategy_set_hash_key,
				record_src,
				strategy_set_id,
                load_dt
            )
            SELECT 
                h.strategy_set_hash_key,
				h.record_src,
				h.strategy_set_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_h tgth
                ON h.record_src = tgth.record_src
				AND h.strategy_set_id = tgth.strategy_set_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.strategy_set_id IS NULL
        """,
    "strategy_set_member_h":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_member_h
            (
                strategy_set_member_hash_key,
				record_src,
				strategy_set_member_id,
                load_dt
            )
            SELECT 
                h.strategy_set_member_hash_key,
				h.record_src,
				h.strategy_set_member_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_member_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_member_h tgth
                ON h.record_src = tgth.record_src
				AND h.strategy_set_member_id = tgth.strategy_set_member_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.strategy_set_member_id IS NULL
        """,
    "weighted_strategy_set_h":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_h
            (
                weighted_strategy_set_hash_key,
				record_src,
				weighted_strategy_set_id,
                load_dt
            )
            SELECT 
                h.weighted_strategy_set_hash_key,
				h.record_src,
				h.weighted_strategy_set_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_h tgth
                ON h.record_src = tgth.record_src
				AND h.weighted_strategy_set_id = tgth.weighted_strategy_set_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.weighted_strategy_set_id IS NULL
        """,
    "weighted_strategy_set_member_h":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_member_h
            (
                weighted_strategy_set_member_hash_key,
				record_src,
				weighted_strategy_set_member_id,
                load_dt
            )
            SELECT 
                h.weighted_strategy_set_member_hash_key,
				h.record_src,
				h.weighted_strategy_set_member_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_member_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_member_h tgth
                ON h.record_src = tgth.record_src
				AND h.weighted_strategy_set_member_id = tgth.weighted_strategy_set_member_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.weighted_strategy_set_member_id IS NULL
        """,
    "game_results_h":
        """
            INSERT INTO dvaz1.sch_tgt1.game_results_h
            (
                game_results_hash_key,
				record_src,
				game_id,
				player_pos_num,
                load_dt
            )
            SELECT 
                h.game_results_hash_key,
				h.record_src,
				h.game_id,
				h.player_pos_num,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.game_results_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.game_results_h tgth
                ON h.record_src = tgth.record_src
				AND h.game_id = tgth.game_id
				AND h.player_pos_num = tgth.player_pos_num
            WHERE
                tgth.record_src IS NULL
				AND tgth.game_id IS NULL
				AND tgth.player_pos_num IS NULL
        """,
    "game_stats_h":
        """
            INSERT INTO dvaz1.sch_tgt1.game_stats_h
            (
                game_stats_hash_key,
				record_src,
				game_id,
                load_dt
            )
            SELECT 
                h.game_stats_hash_key,
				h.record_src,
				h.game_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.game_stats_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.game_stats_h tgth
                ON h.record_src = tgth.record_src
				AND h.game_id = tgth.game_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.game_id IS NULL
        """,
    "competition_grp_h":
        """
            INSERT INTO dvaz1.sch_tgt1.competition_grp_h
            (
                competition_grp_hash_key,
				record_src,
				competition_grp_id,
                load_dt
            )
            SELECT 
                h.competition_grp_hash_key,
				h.record_src,
				h.competition_grp_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.competition_grp_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.competition_grp_h tgth
                ON h.record_src = tgth.record_src
				AND h.competition_grp_id = tgth.competition_grp_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.competition_grp_id IS NULL
        """,
    "competition_grp_member_h":
        """
            INSERT INTO dvaz1.sch_tgt1.competition_grp_member_h
            (
                competition_grp_member_hash_key,
				record_src,
				competition_grp_member_id,
                load_dt
            )
            SELECT 
                h.competition_grp_member_hash_key,
				h.record_src,
				h.competition_grp_member_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.competition_grp_member_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.competition_grp_member_h tgth
                ON h.record_src = tgth.record_src
				AND h.competition_grp_member_id = tgth.competition_grp_member_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.competition_grp_member_id IS NULL
        """,
    "agent_value_h":
        """
            INSERT INTO dvaz1.sch_tgt1.agent_value_h
            (
                agent_value_hash_key,
				record_src,
				agent_value_id,
                load_dt
            )
            SELECT 
                h.agent_value_hash_key,
				h.record_src,
				h.agent_value_id,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.agent_value_h h
                LEFT OUTER JOIN dvaz1.sch_tgt1.agent_value_h tgth
                ON h.record_src = tgth.record_src
				AND h.agent_value_id = tgth.agent_value_id
            WHERE
                tgth.record_src IS NULL
				AND tgth.agent_value_id IS NULL
        """,
    # links
    "strategy_x_strategy_set_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_x_strategy_set_member_l
            (
                strategy_x_strategy_set_member_hash_key,
				record_src,
				strategy_hash_key,
				strategy_set_member_hash_key,
                load_dt
            )
            SELECT 
                l.strategy_x_strategy_set_member_hash_key,
				l.record_src,
				l.strategy_hash_key,
				l.strategy_set_member_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_x_strategy_set_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_x_strategy_set_member_l tgtl
                ON l.strategy_hash_key = tgtl.strategy_hash_key
				AND l.strategy_set_member_hash_key = tgtl.strategy_set_member_hash_key
            WHERE
                tgtl.strategy_hash_key IS NULL
				AND tgtl.strategy_set_member_hash_key IS NULL
        """,
    "strategy_set_x_strategy_set_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_x_strategy_set_member_l
            (
                strategy_set_x_strategy_set_member_hash_key,
				record_src,
				strategy_set_hash_key,
				strategy_set_member_hash_key,
                load_dt
            )
            SELECT 
                l.strategy_set_x_strategy_set_member_hash_key,
				l.record_src,
				l.strategy_set_hash_key,
				l.strategy_set_member_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_x_strategy_set_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_x_strategy_set_member_l tgtl
                ON l.strategy_set_hash_key = tgtl.strategy_set_hash_key
				AND l.strategy_set_member_hash_key = tgtl.strategy_set_member_hash_key
            WHERE
                tgtl.strategy_set_hash_key IS NULL
				AND tgtl.strategy_set_member_hash_key IS NULL
        """,
    "strategy_set_member_x_weighted_strategy_set_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_member_x_weighted_strategy_set_member_l
            (
                strategy_set_member_x_weighted_strategy_set_member_hash_key,
				record_src,
				strategy_set_member_hash_key,
				weighted_strategy_set_member_hash_key,
                load_dt
            )
            SELECT 
                l.strategy_set_member_x_weighted_strategy_set_member_hash_key,
				l.record_src,
				l.strategy_set_member_hash_key,
				l.weighted_strategy_set_member_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_member_x_weighted_strategy_set_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_member_x_weighted_strategy_set_member_l tgtl
                ON l.strategy_set_member_hash_key = tgtl.strategy_set_member_hash_key
				AND l.weighted_strategy_set_member_hash_key = tgtl.weighted_strategy_set_member_hash_key
            WHERE
                tgtl.strategy_set_member_hash_key IS NULL
				AND tgtl.weighted_strategy_set_member_hash_key IS NULL
        """,
    "weighted_strategy_set_x_weighted_strategy_set_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_x_weighted_strategy_set_member_l
            (
                weighted_strategy_set_x_weighted_strategy_set_member_hash_key,
				record_src,
				weighted_strategy_set_hash_key,
				weighted_strategy_set_member_hash_key,
                load_dt
            )
            SELECT 
                l.weighted_strategy_set_x_weighted_strategy_set_member_hash_key,
				l.record_src,
				l.weighted_strategy_set_hash_key,
				l.weighted_strategy_set_member_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_x_weighted_strategy_set_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_x_weighted_strategy_set_member_l tgtl
                ON l.weighted_strategy_set_hash_key = tgtl.weighted_strategy_set_hash_key
				AND l.weighted_strategy_set_member_hash_key = tgtl.weighted_strategy_set_member_hash_key
            WHERE
                tgtl.weighted_strategy_set_hash_key IS NULL
				AND tgtl.weighted_strategy_set_member_hash_key IS NULL
        """,
    "weighted_strategy_set_member_x_competition_grp_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_member_x_competition_grp_member_l
            (
                weighted_strategy_set_member_x_competition_grp_member_hash_key,
				record_src,
				weighted_strategy_set_member_hash_key,
				competition_grp_member_hash_key,
                load_dt
            )
            SELECT 
                l.weighted_strategy_set_member_x_competition_grp_member_hash_key,
				l.record_src,
				l.weighted_strategy_set_member_hash_key,
				l.competition_grp_member_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_member_x_competition_grp_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_member_x_competition_grp_member_l tgtl
                ON l.weighted_strategy_set_member_hash_key = tgtl.weighted_strategy_set_member_hash_key
				AND l.competition_grp_member_hash_key = tgtl.competition_grp_member_hash_key
            WHERE
                tgtl.weighted_strategy_set_member_hash_key IS NULL
				AND tgtl.competition_grp_member_hash_key IS NULL
        """,
    "competition_grp_x_competition_grp_member_l":
        """
            INSERT INTO dvaz1.sch_tgt1.competition_grp_x_competition_grp_member_l
            (
                competition_grp_member_x_competition_grp_hash_key,
				record_src,
				competition_grp_member_hash_key,
				competition_grp_hash_key,
                load_dt
            )
            SELECT 
                l.competition_grp_member_x_competition_grp_hash_key,
				l.record_src,
				l.competition_grp_member_hash_key,
				l.competition_grp_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.competition_grp_x_competition_grp_member_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.competition_grp_x_competition_grp_member_l tgtl
                ON l.competition_grp_member_x_competition_grp_hash_key = tgtl.competition_grp_member_x_competition_grp_hash_key
				AND l.competition_grp_member_hash_key = tgtl.competition_grp_member_hash_key
				AND l.competition_grp_hash_key = tgtl.competition_grp_hash_key
            WHERE
                tgtl.competition_grp_member_x_competition_grp_hash_key IS NULL
				AND tgtl.competition_grp_member_hash_key IS NULL
				AND tgtl.competition_grp_hash_key IS NULL
        """,
    "strategy_set_x_weighted_strategy_set_l":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_x_weighted_strategy_set_l
            (
                strategy_set_x_weighted_strategy_set_hash_key,
				record_src,
				strategy_set_hash_key,
				weighted_strategy_set_hash_key,
                load_dt
            )
            SELECT 
                l.strategy_set_x_weighted_strategy_set_hash_key,
				l.record_src,
				l.strategy_set_hash_key,
				l.weighted_strategy_set_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_x_weighted_strategy_set_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_x_weighted_strategy_set_l tgtl
                ON l.strategy_set_hash_key = tgtl.strategy_set_hash_key
				AND l.weighted_strategy_set_hash_key = tgtl.weighted_strategy_set_hash_key
            WHERE
                tgtl.strategy_set_hash_key IS NULL
				AND tgtl.weighted_strategy_set_hash_key IS NULL
        """,
    "weighted_strategy_set_x_agent_value_l":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_x_agent_value_l
            (
                weighted_strategy_set_x_agent_value_hash_key,
				record_src,
				weighted_strategy_set_hash_key,
				agent_value_hash_key,
                load_dt
            )
            SELECT 
                l.weighted_strategy_set_x_agent_value_hash_key,
				l.record_src,
				l.weighted_strategy_set_hash_key,
				l.agent_value_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_x_agent_value_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_x_agent_value_l tgtl
                ON l.weighted_strategy_set_hash_key = tgtl.weighted_strategy_set_hash_key
				AND l.agent_value_hash_key = tgtl.agent_value_hash_key
            WHERE
                tgtl.weighted_strategy_set_hash_key IS NULL
				AND tgtl.agent_value_hash_key IS NULL
        """,
    "weighted_strategy_set_x_game_results_l":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_x_game_results_l
            (
                weighted_strategy_set_x_game_results_hash_key,
				record_src,
				weighted_strategy_set_hash_key,
				game_results_hash_key,
                load_dt
            )
            SELECT 
                l.weighted_strategy_set_x_game_results_hash_key,
				l.record_src,
				l.weighted_strategy_set_hash_key,
				l.game_results_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_x_game_results_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_x_game_results_l tgtl
                ON l.weighted_strategy_set_hash_key = tgtl.weighted_strategy_set_hash_key
				AND l.game_results_hash_key = tgtl.game_results_hash_key
            WHERE
                tgtl.weighted_strategy_set_hash_key IS NULL
				AND tgtl.game_results_hash_key IS NULL
        """,
    "game_stats_x_game_results_l":
        """
            INSERT INTO dvaz1.sch_tgt1.game_stats_x_game_results_l
            (
                game_stats_x_game_results_hash_key,
				record_src,
				game_stats_hash_key,
				game_results_hash_key,
                load_dt
            )
            SELECT 
                l.game_stats_x_game_results_hash_key,
				l.record_src,
				l.game_stats_hash_key,
				l.game_results_hash_key,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.game_stats_x_game_results_l l
                LEFT OUTER JOIN dvaz1.sch_tgt1.game_stats_x_game_results_l tgtl
                ON l.game_stats_hash_key = tgtl.game_stats_hash_key
				AND l.game_results_hash_key = tgtl.game_results_hash_key
            WHERE
                tgtl.game_stats_hash_key IS NULL
				AND tgtl.game_results_hash_key IS NULL
        """,
    # satellites
    "strategy_s":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_s
            (
                strategy_hash_key,
				record_src,
				hash_diff,
				strategy_txt,
                load_dt
            )
            SELECT 
                s.strategy_hash_key,
				s.record_src,
				s.hash_diff,
				s.strategy_txt,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_s tgts
                ON s.strategy_hash_key = tgts.strategy_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "strategy_set_s":
        """
            INSERT INTO dvaz1.sch_tgt1.strategy_set_s
            (
                strategy_set_hash_key,
				record_src,
				hash_diff,
				strategy_set_txt,
                load_dt
            )
            SELECT 
                s.strategy_set_hash_key,
				s.record_src,
				s.hash_diff,
				s.strategy_set_txt,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.strategy_set_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.strategy_set_s tgts
                ON s.strategy_set_hash_key = tgts.strategy_set_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "weighted_strategy_set_s":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_s
            (
                weighted_strategy_set_hash_key,
				record_src,
				hash_diff,
				weight_summary_num,
                load_dt
            )
            SELECT 
                s.weighted_strategy_set_hash_key,
				s.record_src,
				s.hash_diff,
				s.weight_summary_num,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_s tgts
                ON s.weighted_strategy_set_hash_key = tgts.weighted_strategy_set_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "competition_grp_s":
        """
            INSERT INTO dvaz1.sch_tgt1.competition_grp_s
            (
                competition_grp_hash_key,
				record_src,
				hash_diff,
				set_num,
                load_dt
            )
            SELECT 
                s.competition_grp_hash_key,
				s.record_src,
				s.hash_diff,
				s.set_num,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.competition_grp_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.competition_grp_s tgts
                ON s.competition_grp_hash_key = tgts.competition_grp_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "game_results_s":
        """
            INSERT INTO dvaz1.sch_tgt1.game_results_s
            (
                game_results_hash_key,
				record_src,
				hash_diff,
				score_cnt,
				rank_num,
				win_flg,
                load_dt
            )
            SELECT 
                s.game_results_hash_key,
				s.record_src,
				s.hash_diff,
				s.score_cnt,
				s.rank_num,
				s.win_flg,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.game_results_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.game_results_s tgts
                ON s.game_results_hash_key = tgts.game_results_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "game_stats_s":
        """
            INSERT INTO dvaz1.sch_tgt1.game_stats_s
            (
                game_stats_hash_key,
				record_src,
				hash_diff,
				run_time_secs,
				update_ts,
				finish_flg,
                load_dt
            )
            SELECT 
                s.game_stats_hash_key,
				s.record_src,
				s.hash_diff,
				s.run_time_secs,
				s.update_ts,
				s.finish_flg,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.game_stats_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.game_stats_s tgts
                ON s.game_stats_hash_key = tgts.game_stats_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "weighted_strategy_set_member_s":
        """
            INSERT INTO dvaz1.sch_tgt1.weighted_strategy_set_member_s
            (
                weighted_strategy_set_member_hash_key,
				record_src,
				hash_diff,
				weight_num,
                load_dt
            )
            SELECT 
                s.weighted_strategy_set_member_hash_key,
				s.record_src,
				s.hash_diff,
				s.weight_num,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.weighted_strategy_set_member_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.weighted_strategy_set_member_s tgts
                ON s.weighted_strategy_set_member_hash_key = tgts.weighted_strategy_set_member_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """,
    "agent_value_s":
        """
            INSERT INTO dvaz1.sch_tgt1.agent_value_s
            (
                agent_value_hash_key,
				hash_diff,
				record_src,
				win_rate,
				exec_cnt,
				update_epoch,
                load_dt
            )
            SELECT 
                s.agent_value_hash_key,
				s.hash_diff,
				s.record_src,
				s.win_rate,
				s.exec_cnt,
				s.update_epoch,
                CURRENT_TIMESTAMP()
            FROM dvaz1stg.sch_ld1.agent_value_s s
                LEFT OUTER JOIN dvaz1.sch_tgt1.agent_value_s tgts
                ON s.agent_value_hash_key = tgts.agent_value_hash_key
                AND s.record_src = tgts.record_src
            WHERE
                s.hash_diff <> COALESCE(tgts.hash_diff, 'NoMatch')
                AND tgts.load_end_dt IS NULL
        """
}

updstmts = {
    "strategy_s":
        """
            UPDATE dvaz1.sch_tgt1.strategy_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.strategy_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.strategy_s s1
                JOIN dvaz1.sch_tgt1.strategy_s s2
                ON s1.strategy_hash_key = s2.strategy_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.strategy_s.strategy_hash_key = mxld.strategy_hash_key
                AND dvaz1.sch_tgt1.strategy_s.load_dt = mxld.load_dt
        """,
    "strategy_set_s":
        """
            UPDATE dvaz1.sch_tgt1.strategy_set_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.strategy_set_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.strategy_set_s s1
                JOIN dvaz1.sch_tgt1.strategy_set_s s2
                ON s1.strategy_set_hash_key = s2.strategy_set_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.strategy_set_s.strategy_set_hash_key = mxld.strategy_set_hash_key
                AND dvaz1.sch_tgt1.strategy_set_s.load_dt = mxld.load_dt
        """,
    "weighted_strategy_set_s":
        """
            UPDATE dvaz1.sch_tgt1.weighted_strategy_set_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.weighted_strategy_set_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.weighted_strategy_set_s s1
                JOIN dvaz1.sch_tgt1.weighted_strategy_set_s s2
                ON s1.weighted_strategy_set_hash_key = s2.weighted_strategy_set_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.weighted_strategy_set_s.weighted_strategy_set_hash_key = mxld.weighted_strategy_set_hash_key
                AND dvaz1.sch_tgt1.weighted_strategy_set_s.load_dt = mxld.load_dt
        """,
    "competition_grp_s":
        """
            UPDATE dvaz1.sch_tgt1.competition_grp_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.competition_grp_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.competition_grp_s s1
                JOIN dvaz1.sch_tgt1.competition_grp_s s2
                ON s1.competition_grp_hash_key = s2.competition_grp_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.competition_grp_s.competition_grp_hash_key = mxld.competition_grp_hash_key
                AND dvaz1.sch_tgt1.competition_grp_s.load_dt = mxld.load_dt
        """,
    "game_results_s":
        """
            UPDATE dvaz1.sch_tgt1.game_results_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.game_results_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.game_results_s s1
                JOIN dvaz1.sch_tgt1.game_results_s s2
                ON s1.game_results_hash_key = s2.game_results_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.game_results_s.game_results_hash_key = mxld.game_results_hash_key
                AND dvaz1.sch_tgt1.game_results_s.load_dt = mxld.load_dt
        """,
    "game_stats_s":
        """
            UPDATE dvaz1.sch_tgt1.game_stats_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.game_stats_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.game_stats_s s1
                JOIN dvaz1.sch_tgt1.game_stats_s s2
                ON s1.game_stats_hash_key = s2.game_stats_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.game_stats_s.game_stats_hash_key = mxld.game_stats_hash_key
                AND dvaz1.sch_tgt1.game_stats_s.load_dt = mxld.load_dt
        """,
    "weighted_strategy_set_member_s":
        """
            UPDATE dvaz1.sch_tgt1.weighted_strategy_set_member_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.weighted_strategy_set_member_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.weighted_strategy_set_member_s s1
                JOIN dvaz1.sch_tgt1.weighted_strategy_set_member_s s2
                ON s1.weighted_strategy_set_member_hash_key = s2.weighted_strategy_set_member_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.weighted_strategy_set_member_s.weighted_strategy_set_member_hash_key = mxld.weighted_strategy_set_member_hash_key
                AND dvaz1.sch_tgt1.weighted_strategy_set_member_s.load_dt = mxld.load_dt
        """,
    "agent_value_s":
        """
            UPDATE dvaz1.sch_tgt1.agent_value_s
            SET load_end_dt = mxld.next_ld_dt
            FROM
            (
            SELECT
                s1.agent_value_hash_key,
                s1.load_dt,
                MIN(s2.load_dt) next_ld_dt
            FROM dvaz1.sch_tgt1.agent_value_s s1
                JOIN dvaz1.sch_tgt1.agent_value_s s2
                ON s1.agent_value_hash_key = s2.agent_value_hash_key
            WHERE s1.load_dt < s2.load_dt
                AND s1.load_end_dt IS NULL
            GROUP BY 1,2
            ) mxld
           WHERE dvaz1.sch_tgt1.agent_value_s.agent_value_hash_key = mxld.agent_value_hash_key
                AND dvaz1.sch_tgt1.agent_value_s.load_dt = mxld.load_dt
        """
}

cr8stmts = {
    "strategy_h": """CREATE TABLE dvaz1stg.sch_ld1.strategy_h
    (
        record_src VARCHAR(40),
        strategy_hash_key CHAR(32) NOT NULL,
        strategy_id BIGINT NOT NULL,
        PRIMARY KEY(strategy_hash_key)
    )""",
    
    
    "strategy_set_h": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_h
    (
        record_src VARCHAR(40),
        strategy_set_hash_key CHAR(32) NOT NULL,
        strategy_set_id BIGINT NOT NULL,
        PRIMARY KEY(strategy_set_hash_key)
    )""",
    
    
    "strategy_set_member_h": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_member_h
    (
        record_src VARCHAR(40),
        strategy_set_member_hash_key CHAR(32) NOT NULL,
        strategy_set_member_id BIGINT NOT NULL,
        PRIMARY KEY(strategy_set_member_hash_key)
    )""",
    
    
    "weighted_strategy_set_h": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_h
    (
        record_src VARCHAR(40),
        weighted_strategy_set_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_id BIGINT NOT NULL,
        PRIMARY KEY(weighted_strategy_set_hash_key)
    )""",
    
    
    "weighted_strategy_set_member_h": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_member_h
    (
        record_src VARCHAR(40),
        weighted_strategy_set_member_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_member_id BIGINT NOT NULL,
        PRIMARY KEY(weighted_strategy_set_member_hash_key)
    )""",
    
    
    "game_results_h": """CREATE TABLE dvaz1stg.sch_ld1.game_results_h
    (
        record_src VARCHAR(40),
        game_results_hash_key CHAR(32) NOT NULL,
        game_id BIGINT NOT NULL,
        player_pos_num SMALLINT NOT NULL,
        PRIMARY KEY(game_results_hash_key)
    )""",
    
    
    "game_stats_h": """CREATE TABLE dvaz1stg.sch_ld1.game_stats_h
    (
        record_src VARCHAR(40),
        game_stats_hash_key CHAR(32) NOT NULL,
        game_id BIGINT NOT NULL,
        PRIMARY KEY(game_stats_hash_key)
    )""",
    
    
    "competition_grp_h": """CREATE TABLE dvaz1stg.sch_ld1.competition_grp_h
    (
        record_src VARCHAR(40),
        competition_grp_hash_key CHAR(32) NOT NULL,
        competition_grp_id BIGINT NOT NULL,
        PRIMARY KEY(competition_grp_hash_key)
    )""",
    
    
    "competition_grp_member_h": """CREATE TABLE dvaz1stg.sch_ld1.competition_grp_member_h
    (
        record_src VARCHAR(40),
        competition_grp_member_hash_key CHAR(32) NOT NULL,
        competition_grp_member_id BIGINT NOT NULL,
        PRIMARY KEY(competition_grp_member_hash_key)
    )""",
    
    
    "agent_value_h": """CREATE TABLE dvaz1stg.sch_ld1.agent_value_h
    (
        record_src VARCHAR(40),
        agent_value_hash_key CHAR(32) NOT NULL,
        agent_value_id BIGINT NOT NULL,
        PRIMARY KEY(agent_value_hash_key)
    )""",
    
    
    "strategy_x_strategy_set_member_l": """CREATE TABLE dvaz1stg.sch_ld1.strategy_x_strategy_set_member_l
    (
        record_src VARCHAR(40),
        strategy_x_strategy_set_member_hash_key CHAR(32) NOT NULL,
        strategy_hash_key CHAR(32),
        strategy_set_member_hash_key CHAR(32),
        PRIMARY KEY(strategy_x_strategy_set_member_hash_key)
    )""",
    
    
    "strategy_set_x_strategy_set_member_l": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_x_strategy_set_member_l
    (
        record_src VARCHAR(40),
        strategy_set_x_strategy_set_member_hash_key CHAR(32) NOT NULL,
        strategy_set_hash_key CHAR(32),
        strategy_set_member_hash_key CHAR(32),
        PRIMARY KEY(strategy_set_x_strategy_set_member_hash_key)
    )""",
    
    
    "strategy_set_member_x_weighted_strategy_set_member_l": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_member_x_weighted_strategy_set_member_l
    (
        record_src VARCHAR(40),
        strategy_set_member_x_weighted_strategy_set_member_hash_key CHAR(32) NOT NULL,
        strategy_set_member_hash_key CHAR(32),
        weighted_strategy_set_member_hash_key CHAR(32),
        PRIMARY KEY(strategy_set_member_x_weighted_strategy_set_member_hash_key)
    )""",
    
    
    "weighted_strategy_set_x_weighted_strategy_set_member_l": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_x_weighted_strategy_set_member_l
    (
        record_src VARCHAR(40),
        weighted_strategy_set_x_weighted_strategy_set_member_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_hash_key CHAR(32),
        weighted_strategy_set_member_hash_key CHAR(32),
        PRIMARY KEY(weighted_strategy_set_x_weighted_strategy_set_member_hash_key)
    )""",
    
    
    "weighted_strategy_set_member_x_competition_grp_member_l": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_member_x_competition_grp_member_l
    (
        record_src VARCHAR(40),
        weighted_strategy_set_member_x_competition_grp_member_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_member_hash_key CHAR(32),
        competition_grp_member_hash_key CHAR(32),
        PRIMARY KEY(weighted_strategy_set_member_x_competition_grp_member_hash_key)
    )""",
    
    
    "competition_grp_x_competition_grp_member_l": """CREATE TABLE dvaz1stg.sch_ld1.competition_grp_x_competition_grp_member_l
    (
        record_src VARCHAR(40),
        competition_grp_member_x_competition_grp_hash_key CHAR(32) NOT NULL,
        competition_grp_member_hash_key CHAR(32),
        competition_grp_hash_key CHAR(32),
        PRIMARY KEY(competition_grp_member_x_competition_grp_hash_key)
    )""",
    
    
    "strategy_set_x_weighted_strategy_set_l": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_x_weighted_strategy_set_l
    (
        record_src VARCHAR(40),
        strategy_set_x_weighted_strategy_set_hash_key CHAR(32) NOT NULL,
        strategy_set_hash_key CHAR(32),
        weighted_strategy_set_hash_key CHAR(32),
        PRIMARY KEY(strategy_set_x_weighted_strategy_set_hash_key)
    )""",
    
    
    "weighted_strategy_set_x_agent_value_l": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_x_agent_value_l
    (
        record_src VARCHAR(40),
        weighted_strategy_set_x_agent_value_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_hash_key CHAR(32),
        agent_value_hash_key CHAR(32),
        PRIMARY KEY(weighted_strategy_set_x_agent_value_hash_key)
    )""",
    
    
    "weighted_strategy_set_x_game_results_l": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_x_game_results_l
    (
        record_src VARCHAR(40),
        weighted_strategy_set_x_game_results_hash_key CHAR(32) NOT NULL,
        weighted_strategy_set_hash_key CHAR(32),
        game_results_hash_key CHAR(32),
        PRIMARY KEY(weighted_strategy_set_x_game_results_hash_key)
    )""",
    
    
    "game_stats_x_game_results_l": """CREATE TABLE dvaz1stg.sch_ld1.game_stats_x_game_results_l
    (
        record_src VARCHAR(40),
        game_stats_x_game_results_hash_key CHAR(32) NOT NULL,
        game_stats_hash_key CHAR(32),
        game_results_hash_key CHAR(32),
        PRIMARY KEY(game_stats_x_game_results_hash_key)
    )""",
    
    
    "strategy_s": """CREATE TABLE dvaz1stg.sch_ld1.strategy_s
    (
        record_src VARCHAR(40),
        strategy_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        strategy_txt VARCHAR(80),
        PRIMARY KEY(strategy_hash_key)
    )""",
    
    
    "strategy_set_s": """CREATE TABLE dvaz1stg.sch_ld1.strategy_set_s
    (
        record_src VARCHAR(40),
        strategy_set_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        strategy_set_txt VARCHAR(512),
        PRIMARY KEY(strategy_set_hash_key)
    )""",
    
    
    "weighted_strategy_set_s": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_s
    (
        record_src VARCHAR(40),
        weighted_strategy_set_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        weight_summary_num VARCHAR(20),
        PRIMARY KEY(weighted_strategy_set_hash_key)
    )""",
    
    
    "competition_grp_s": """CREATE TABLE dvaz1stg.sch_ld1.competition_grp_s
    (
        record_src VARCHAR(40),
        competition_grp_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        comp_grp_descr VARCHAR(1023),
        set_num VARCHAR(10),
        PRIMARY KEY(competition_grp_hash_key)
    )""",
    
    
    "game_results_s": """CREATE TABLE dvaz1stg.sch_ld1.game_results_s
    (
        record_src VARCHAR(40),
        game_results_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        score_cnt VARCHAR(4) NOT NULL,
        rank_num VARCHAR(2) NULL,
        win_flg CHAR(1) NULL,
        PRIMARY KEY(game_results_hash_key)
    )""",
    
    
    "game_stats_s": """CREATE TABLE dvaz1stg.sch_ld1.game_stats_s
    (
        record_src VARCHAR(40),
        game_stats_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        run_time_secs VARCHAR(20) NULL,
        update_ts VARCHAR(80) NULL,
        finish_flg CHAR(1) NULL,
        PRIMARY KEY(game_stats_hash_key)
    )""",
    
    
    "weighted_strategy_set_member_s": """CREATE TABLE dvaz1stg.sch_ld1.weighted_strategy_set_member_s
    (
        record_src VARCHAR(40),
        weighted_strategy_set_member_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        weight_num VARCHAR(20),
        PRIMARY KEY(weighted_strategy_set_member_hash_key)
    )""",
    
    
    "agent_value_s": """CREATE TABLE dvaz1stg.sch_ld1.agent_value_s
    (
        record_src VARCHAR(40),
        agent_value_hash_key CHAR(32) NOT NULL,
        hash_diff CHAR(32),
        win_rate VARCHAR(32) NULL,
        exec_cnt VARCHAR(12) NULL,
        update_epoch VARCHAR(24) NULL,
        PRIMARY KEY(agent_value_hash_key)
    )"""

}
